In [2]:
import pandas as pd 
import sqlite3

In [16]:
# Connect to the ChEMBL database
conn = sqlite3.connect("../data/raw/chembl_36.db")
cursor = conn.cursor()

In [5]:
# List of tables in the ChEMBL database
tables = pd.read_sql("""
                    Select name 
                    From sqlite_master
                    WHERE type ="table";""", conn)
tables

                         name
0                 action_type
1                  assay_type
2            chembl_id_lookup
3     confidence_score_lookup
4             curation_lookup
..                        ...
69   pesticide_classification
70  predicted_binding_domains
71               warning_refs
72    pesticide_class_mapping
73               sqlite_stat1

[74 rows x 1 columns]

In [6]:
pd.read_sql("SELECT COUNT(*) FROM activities", conn)

   COUNT(*)
0  24267312

In [11]:
pd.read_sql("SELECT COUNT(*) FROM molecule_dictionary", conn)

   COUNT(*)
0   2878135

In [12]:
pd.read_sql("PRAGMA table_info(activities)", conn)

    cid                   name           type  notnull dflt_value  pk
0     0            activity_id         BIGINT        1       None   1
1     1               assay_id         BIGINT        1       None   0
2     2                 doc_id         BIGINT        0       None   0
3     3              record_id         BIGINT        1       None   0
4     4               molregno         BIGINT        0       None   0
5     5      standard_relation    VARCHAR(50)        0       None   0
6     6         standard_value        NUMERIC        0       None   0
7     7         standard_units   VARCHAR(100)        0       None   0
8     8          standard_flag       SMALLINT        0       None   0
9     9          standard_type   VARCHAR(250)        0       None   0
10   10       activity_comment  VARCHAR(4000)        0       None   0
11   11  data_validity_comment    VARCHAR(30)        0       None   0
12   12    potential_duplicate       SMALLINT        0       None   0
13   13          pchembl_value  NUMERIC(4, 2)        0       None   0
14   14           bao_endpoint    VARCHAR(11)        0       None   0
15   15               uo_units    VARCHAR(10)        0       None   0
16   16             qudt_units    VARCHAR(70)        0       None   0
17   17                   toid        INTEGER        0       None   0
18   18            upper_value        NUMERIC        0       None   0
19   19   standard_upper_value        NUMERIC        0       None   0
20   20                 src_id        INTEGER        0       None   0
21   21                   type   VARCHAR(250)        1       None   0
22   22               relation    VARCHAR(50)        0       None   0
23   23                  value        NUMERIC        0       None   0
24   24                  units   VARCHAR(100)        0       None   0
25   25             text_value  VARCHAR(1000)        0       None   0
26   26    standard_text_value  VARCHAR(1000)        0       None   0
27   27            action_type    VARCHAR(50)        0       None   0

In [18]:
df = pd.read_sql_query(
    "SELECT * FROM activities LIMIT 5;",
    conn
)

print(df)

   activity_id  assay_id  doc_id  record_id  molregno standard_relation  \
0        31863     54505    6424     206172    180094                 >
1        31864     83907    6432     208970    182268                 =
2        31865     88152    6432     208970    182268                 >
3        31866     83907    6432     208987    182855                 =
4        31867     88153    6432     208987    182855              None

   standard_value standard_units  standard_flag standard_type  ...  \
0        100000.0             nM              1          IC50  ...
1          2500.0             nM              1          IC50  ...
2         50000.0             nM              1          IC50  ...
3          9000.0             nM              1          IC50  ...
4             NaN             nM              0          IC50  ...

  upper_value standard_upper_value  src_id  type relation  value units  \
0        None                 None       1  IC50        >  100.0    uM
1        None                 None       1  IC50        =    2.5    uM
2        None                 None       1  IC50        >   50.0    uM
3        None                 None       1  IC50        =    9.0    uM
4        None                 None       1  IC50     None    NaN    uM

  text_value standard_text_value action_type
0       None                None        None
1       None                None        None
2       None                None        None
3       None                None        None
4       None                None        None

[5 rows x 28 columns]